### PR TITLE
Addition of drt messages

### PR DESCRIPTION
**Pull request by thomastrillium**
Adds suggested fields drt_pickup_message and drt_drop_off_message

### CODE REVIEW

**Comment by thomastrillium** [comment]
This PR suggests two new fields, added to trips.txt in addition to the fields `drt_max_travel_time` `drt_avg_travel_time` and `drt_advance_book_min`.

`drt_pickup_message` and `drt_drop_off_message` are text messages that should be communicated to an application user, when they are provided a trip plan that utilizes a drt service (defined here as "vehicle travel off the fixed route alignment", ie dial-a-ride or deviated-fixed).

Theoretically a standard message could be autogenerated based off the `agency_phone` and `drt_advance_book_min` fields. For example, "The identified route will pickup/drop off if scheduled [`drt_advance_book_min`] hours in advance by calling [`agency_phone`]". However, many subtle variations of this type of language may be required, and it may differ between pickup and drop off.

A big open question to me on this note that I'd like feedback on: should links be allowed? if so, how would they be formatted?

**Comment by barbeau** [comment]
@thomastrillium Thanks for putting this together!  A few quick comments:

1. IMHO, the contents of the field should stand alone, with no links to other fields.
1. One challenge here is the expectation for how long this text is - for example, in a web-based trip planner mainly used on desktops this could be a paragraph, while mobile devices would want something shorter.  So, I think we should establish some guidance/expectation for the length of the text here, and provide some examples of how they would be shown.  Off the top of my head I'm not aware of line-length limitations for any CSV reading/writing libraries, but that's something to check as well.  We'd also need to make sure that any special characters like commas are properly escaped (although IIRC, this guidance is already be part of GTFS).
1. A big challenge here is translations - for this type of free text, I would imagine that agencies would want some type of ability to provide text in more than one language, similar to [service alert](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-translatedstring) translations.  One option would be to prefix or suffix the field name with the BCP-47 language code (e.g., `en` for English, `es` for Spanish), and have support for multiple columns, each column being a different language.  IIRC we don't handle with translations anywhere else in the GTFS spec, only GTFS-realtime Service Alerts.

**Comment by sdjacobs** [comment]
Would it be reasonable to put the explanation of how to board or alight a DRT service in the `route_desc` field, rather than creating a new field?

From the [spec](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt):

> The route_desc field contains a description of a route. Please provide useful, quality information. Do not simply duplicate the name of the route. For example, "A trains operate between Inwood-207 St, Manhattan and Far Rockaway-Mott Avenue, Queens at all times. Also from about 6AM until about midnight, additional A trains operate between Inwood-207 St and Lefferts Boulevard (trains typically alternate between Lefferts Blvd and Far Rockaway)."

For what it's worth, `route_desc` has the same issues @barbeau raised - translation and length concerns.

**Comment by thomastrillium** [comment]
My thought is that 

1. This field may already be in use for other purposes (we use this field for GTFS feeds that are processed by web sites we manage, to populate a brief field at the top of the route page describing the route more generally)
2. There may be different messages that should be delivered based on whether there is a dropoff or pickup, or even different message during different parts of the route. (I'm thinking of a route that has different requirements for one segment than another, or different rules going to a transit center as opposed to from, regardless of whether pickup or dropoff.
3. Seems like we could help address the field length concerns by having a field that has a very tailored use case.

That said, I'm sensitive to spec bloat and agree in principle that we should avoid more changes to spec than necessary. Maybe this suggestion is too tailored to our UI concern. I'd love to hear any other thoughts from @antrim @barbeau and @nihit-jain-ibigroup

**Comment by barbeau** [comment]
I agree that re-using `route_desc` for this probably isn't a good idea for legacy use reasons, and the below:

>There may be different messages that should be delivered based on whether there is a dropoff or pickup, or even different message during different parts of the route

I agree

>Seems like we could help address the field length concerns by having a field that has a very tailored use case.

I agree - I think we need a tight description of what is expected and some example use cases to help producers understand exactly how consumers plan to use this info.

@thomastrillium Do you have any current real use cases you could share that might help with this?

**Comment by thomastrillium** [comment]
I've attempted to address this concern by specifying that this is for the "minimum information" to be transmitted, and suggesting venues for more information if applicable.

I've also added separate `continuous_pickup_message` and `continuous_drop_off_message`so that we can differentiate between messages for demand responsive and flag stopping services.

side note: I'm starting to realize that there are two distinct service types: drt and continuous stopping. I'm not sure what this means, but i'm stewing on how we could potentially clarify what GTFS-flex does by classifying everything more clearly as one of those two things.

**Pull request merged**
