### PR TITLE
Addition of sample RTD GTFS-flex files for Call-n-Ride service.

### PR DESCRIPTION
**Pull request by nihit-jain-ibigroup**
The Regional Transportation District (RTD, Denver, CO, USA) has created a draft set of GTFS-flex files modeled for their Call-n-Ride service. This set of draft files is being provided here to enable users to download, review, comment, and suggest improvements both to the files, as well as the GTFS-flex specification.
More information on the Call-n-Ride service here... http://www.rtd-denver.com/callNRide.shtml

### CODE REVIEW

**Comment by barbeau** [comment]
@nihit-jain-ibigroup Thanks!  Did you mean to alter the spec/GTFS and GTFS-flex.jpg file in this PR?  If so, could you explain the changes here?

**Comment by nihit-jain-ibigroup** [comment]
@barbeau I initially didn't mean to change the diagram because I thought it had been updated previously. But when I made the pull request, Github actually suggested that the old diagram update I had made hadn't been merged. The previous diagram wasn't correct since in the original file, it showed colors for required files as optional, and vice versa (as in this diagram below). This had been updated in the Google image version but I believe the update might not have been carried over into Github.  

gtfs-flex_diagupdt

**Comment by barbeau** [comment]
Thanks @nihit-jain-ibigroup!  In the future you'll want to create a new Git branch for each change, and that way commits from separate changes won't get mixed in the same pull request.  I've squashed and merged these changes into a single commit with a description of each change.

**Comment by nihit-jain-ibigroup** [comment]
Thanks @barbeau and noted. I will make sure to do this in the future!!

**Pull request merged**
