### PR TITLE
New transfers.txt fields

### PR DESCRIPTION
**Pull request by thomastrillium**
Added suggested field and edited two fields in transfers.txt to
indicate preferred transfers between flex routes and non-flexible
services.

### CODE REVIEW

**Comment by sdjacobs** [comment]
@thomastrillium - have you seen this similar [PR](https://github.com/google/transit/pull/32) in the GTFS spec from @antrim? This would add `from_route_id` and `to_route_id` to `transfers.txt`, among other changes. There's also quite a long discussion about whether to break backwards compatibility of block transfers, since many feed producers use `block_id` to indicate that trips are served by the same vehicle, rather than that an in-seat block transfer is necessarily permissible. I believe this issue is what held that PR up from being merged.

I'd suggest either trying to get that PR merged, or implementing this PR in a way that's more in harmony with that one, i.e. using `from_route_id` and `to_route_id` rather than `route_id`.

**Comment by sdjacobs** [comment]
Actually, on second read, looks like that PR wasn't merged because it's required that a feed producer and consumer implement GTFS changes before they're merged. We may satisfy that requirement for a subset of the PR.

**Comment by thomastrillium** [comment]
Whoops! missed this. I had been more focused on the in seat transfer part of that PR and totally forgot about the Google extension.

It's unnecessarily complex for our use case, but there are other use cases, and it already has community support.

Based on Andrew's comment, it sounds like these fields are already in OTP? Can you confirm and give a short description of how OTP uses them?

**Comment by thomastrillium** [comment]
OK. I had some concerns that the model might be a bit burdensome but Simon gave me the full context off thread and I retract this PR. I'll delete the branch. Thanks @sdjacobs !

**Pull request closed without merging**
